### ISSUE TITLE
Would be perfect if image preview is supported, if possible

### ISSUE THREAD

**Issue by thedavidweng** [jw-12138/r2-uploader#1]
如果有可能实现图片预览就完美了

**Comment by jw-12138** [comment]
谢谢反馈，但是这个工具的设计理念就是“upload & forget”，我自己也是用户，但是我可能就不太会纠结上传的时候是不是有图片预览，因为我在上传的时候就能明确知道我究竟选择了哪些文件，而且即使你不小心上传了错误的文件，也能非常简单的删除掉。所以这个功能我可能近期不会考虑，不好意思啦！
