### ISSUE TITLE
upload failed

### ISSUE THREAD

**Issue by fys05** [jw-12138/r2-uploader#11]
<img width="1427" alt="截屏2024-09-26 17 53 23" src="https://github.com/user-attachments/assets/54986441-3c59-4b36-a348-bcdd3109604b">
I have completed the operation according to the document, and when I opened the uploader page, I encountered these errors. The page indicates that the file upload has been completed, but in reality, it cannot be seen in the r2 bucket. Could you please clarify this? Thank you

**Comment by jw-12138** [comment]
@fys05 could you please provide more details?

- is your cf-worker working properly? (try uploading a small file using postman or whatever api testing tools you like)
  - url: `<worker_url>/<file_name>`
  - headers
    - `x-api-key`: `your_api_key`
  - body: `<file>`
- how big is the file you were uploading?
  - if the file were bigger than 95Mb, check the api `GET <worker_url>/support_mpu`, this api should return `yes`, if not, try re-deploy the worker with this repo: [r2-uploader-example-worker](https://github.com/jw-12138/r2-uploader-example-worker)
