### ISSUE TITLE
How to upload files larger than 300mb？

### ISSUE THREAD

**Issue by 8824PPZ** [jw-12138/r2-uploader#13]
If you have achieved it, could you please give me a configuration tutorial? Thanks.

**Comment by jw-12138** [comment]
please refer to the [Set Up the Worker](https://github.com/jw-12138/r2-uploader?tab=readme-ov-file#set-up-the-worker-%EF%B8%8F) section, the refactored version of worker should be able to upload a single file that is up to 100Gb.
