### ISSUE TITLE
Multipart rename upload fails (attempts to complete with original filename)

### ISSUE THREAD

**Issue by spurin** [jw-12138/r2-uploader#6]
Hi @jw-12138,

I've switched over to the updated code base and when using the multipart upload, it fails to complete when using the rename option. If I toggle off the rename option, all works as expected.

In the network inspector I can see that it's attempting to call mpu/complete/filename using the original filename, rather than the renamed filename.

Raising this here but I'm guessing, this is possibly an issue relating to https://github.com/jw-12138/r2-uploader-example-worker

Many Thanks

James

**Comment by spurin** [comment]
Screenshot:

Filename uploaded with rename option, gets to 100% and gets stuck -

<img width="499" alt="image" src="https://github.com/user-attachments/assets/8b6ad131-fc3d-49c5-a0ec-51642598d5f5">

---

Each part is using the renamed filename -

<img width="737" alt="image" src="https://github.com/user-attachments/assets/068e2140-7750-4fea-be66-52a4754b68bd">

---

Request made to mpu/complete (incorrectly using the original filename and failing)

<img width="754" alt="image" src="https://github.com/user-attachments/assets/5eb5b0db-70db-4393-ba98-29bb1dfa45f6">

<img width="713" alt="image" src="https://github.com/user-attachments/assets/ced44c5d-e5ce-4b33-bdb3-a1ab56d33077">

**Comment by spurin** [comment]
Further to my last update, I've been experimenting with Vercel which I doubt I would have looked at without this project, it's superb :-)

From my own branch, I've implemented a fix, tested and raised a pull request above.

**Comment by jw-12138** [comment]
this PR has been merged and deployed to [r2.jw1.dev](https://r2.jw1.dev), thanks for that! 

what a silly mistake i've made 😵‍💫

**Comment by jw-12138** [comment]
also did a refactor, all mpu-related functions are now using the `fileName` formatted from the `uploadFile` function so we don't have to read the value again.

<img width="310" alt="image" src="https://github.com/user-attachments/assets/4bc6ad2c-6582-4a32-bd28-9fcf23823a08">

**Comment by jw-12138** [comment]
@spurin thanks again for the PR, the client side code is a mess and poorly documented, yet you still put this much efforts on it ❤️😭!

**Comment by spurin** [comment]
Many thanks again @jw-12138 

Love this project and also appreciate your timely help and support 🙌
