### ISSUE TITLE
feature request: uploader batch export/copy files URLs

### ISSUE THREAD

**Issue by paperpeel** [jw-12138/r2-uploader#8]
Thanks for your great works. It's even faster than CF dashboard. Amazing!

**Comment by paperpeel** [comment]
I tried this works for me https://github.com/jw-12138/r2-uploader/pull/9

**Comment by jw-12138** [comment]
@paperpeel awesome, thx for the PR!

i've optimized the buttons with a state called selection mode, and optimized the style when user successfully copied the urls, `alert()` is way too heavy for this kinda interactions, so i moved the text to the button.

<img width="254" alt="image" src="https://github.com/user-attachments/assets/86d0c1fe-eaaf-44c4-a0c7-cb23e912ee75">

<img width="245" alt="image" src="https://github.com/user-attachments/assets/509e4a3b-21f2-4386-8eaa-822b1c4481ff">

<img width="247" alt="image" src="https://github.com/user-attachments/assets/9a608e88-1a2b-459b-8ff0-2ff4f0a9093d">
